POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "neiva", "password": "j7m!jo[68HV%", "email": "neiva@gmail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "neiva", "password": "j7m!jo[68HV%" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: Token 196f33f429f754677f96ac959df160e10258b9b8