POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "teste", "password": "<<1{z;Y5r71f", "email": "teste@gmail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "teste", "password": "<<1{z;Y5r71f" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: Token 76ca4035174084fa2dfdebaea18adaff364e0e3f