# Generated by Django 4.1.3 on 2023-11-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capyba', '0002_rename_nome_usuario_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
